import type { Team } from './types';

export const INITIAL_TEAMS: Team[] = [
  // ─── GRUPO A ──────────────────────────────────────────────────────────────
  {
    id: "mex", name: "México", group: "A",
    flagUrl: "https://flagcdn.com/w160/mx.png",
    ranking: 16, worldCupWins: 0, titles: [],
    description: "Tricampeão da CONCACAF, o México é presença garantida em Copas e vencedor do Grupo A em 2026.",
    isUnbeaten: false,
  },
  {
    id: "rsa", name: "África do Sul", group: "A",
    flagUrl: "https://flagcdn.com/w160/za.png",
    ranking: 62, worldCupWins: 0, titles: [],
    description: "Sede da Copa 2010, a África do Sul fez história ao avançar do Grupo A em 2026.",
    isUnbeaten: false,
  },
  {
    id: "kor", name: "Coreia do Sul", group: "A",
    flagUrl: "https://flagcdn.com/w160/kr.png",
    ranking: 22, worldCupWins: 0, titles: [],
    description: "Semifinalista em 2002, a Coreia do Sul é uma das potências asiáticas do futebol.",
    isUnbeaten: false,
  },
  {
    id: "cze", name: "Tchéquia", group: "A",
    flagUrl: "https://flagcdn.com/w160/cz.png",
    ranking: 37, worldCupWins: 0, titles: [],
    description: "Herdeira da tradição da Tchecoslováquia, bicampeã mundial em 1934 e 1938.",
    isUnbeaten: false,
  },
  // ─── GRUPO B ──────────────────────────────────────────────────────────────
  {
    id: "can", name: "Canadá", group: "B",
    flagUrl: "https://flagcdn.com/w160/ca.png",
    ranking: 43, worldCupWins: 0, titles: [],
    description: "Co-sede da Copa 2026, o Canadá virou anfitrião e sonhador em seu próprio torneio.",
    isUnbeaten: false,
  },
  {
    id: "sui", name: "Suíça", group: "B",
    flagUrl: "https://flagcdn.com/w160/ch.png",
    ranking: 19, worldCupWins: 0, titles: [],
    description: "Seleção consistente e organizada, liderou o Grupo B com 7 pontos em 2026.",
    isUnbeaten: false,
  },
  {
    id: "qat", name: "Catar", group: "B",
    flagUrl: "https://flagcdn.com/w160/qa.png",
    ranking: 58, worldCupWins: 0, titles: [],
    description: "Sede da Copa 2022, o Catar volta a representar a Ásia em sua segunda Copa do Mundo.",
    isUnbeaten: false,
  },
  {
    id: "bih", name: "Bósnia e H.", group: "B",
    flagUrl: "https://flagcdn.com/w160/ba.png",
    ranking: 55, worldCupWins: 0, titles: [],
    description: "Seleção jovem com talentos na Europa, avançou como terceiro melhor no Grupo B.",
    isUnbeaten: false,
  },
  // ─── GRUPO C ──────────────────────────────────────────────────────────────
  {
    id: "bra", name: "Brasil", group: "C",
    subtitle: "5x Campeão",
    flagUrl: "https://flagcdn.com/w160/br.png",
    ranking: 5, worldCupWins: 5, titles: ["1958", "1962", "1970", "1994", "2002"],
    description: "A Canarinho é a maior vencedora da história com 5 títulos mundiais. Liderou o Grupo C em 2026 com 7 pontos.",
    isUnbeaten: false,
  },
  {
    id: "mar", name: "Marrocos", group: "C",
    flagUrl: "https://flagcdn.com/w160/ma.png",
    ranking: 14, worldCupWins: 0, titles: [],
    description: "Semifinalista em 2022, Marrocos avançou novamente da fase de grupos em 2026.",
    isUnbeaten: false,
  },
  {
    id: "sco", name: "Escócia", group: "C",
    flagUrl: "https://flagcdn.com/w160/gb-sct.png",
    ranking: 34, worldCupWins: 0, titles: [],
    description: "Uma das seleções mais antigas do futebol, a Escócia disputou o Grupo C com garra.",
    isUnbeaten: false,
  },
  {
    id: "hai", name: "Haiti", group: "C",
    flagUrl: "https://flagcdn.com/w160/ht.png",
    ranking: 80, worldCupWins: 0, titles: [],
    description: "Representando o Caribe com orgulho, o Haiti participou de sua segunda Copa do Mundo.",
    isUnbeaten: false,
  },
  // ─── GRUPO D ──────────────────────────────────────────────────────────────
  {
    id: "usa", name: "EUA", group: "D",
    flagUrl: "https://flagcdn.com/w160/us.png",
    ranking: 11, worldCupWins: 0, titles: [],
    description: "Co-sede da Copa 2026 e líder do Grupo D. O futebol americano cresce a cada edição.",
    isUnbeaten: false,
  },
  {
    id: "par", name: "Paraguai", group: "D",
    flagUrl: "https://flagcdn.com/w160/py.png",
    ranking: 49, worldCupWins: 0, titles: [],
    description: "Conhecida pela solidez defensiva, o Paraguai avançou como um dos melhores terceiros colocados.",
    isUnbeaten: false,
  },
  {
    id: "aus", name: "Austrália", group: "D",
    flagUrl: "https://flagcdn.com/w160/au.png",
    ranking: 23, worldCupWins: 0, titles: [],
    description: "Semifinalista em 2022, a Austrália avançou do Grupo D em 2026 como vice-líder.",
    isUnbeaten: false,
  },
  {
    id: "tur", name: "Turquia", group: "D",
    flagUrl: "https://flagcdn.com/w160/tr.png",
    ranking: 39, worldCupWins: 0, titles: [],
    description: "Terceiro lugar em 2002, a Turquia foi eliminada na fase de grupos em 2026.",
    isUnbeaten: false,
  },
  // ─── GRUPO E ──────────────────────────────────────────────────────────────
  {
    id: "ger", name: "Alemanha", group: "E",
    flagUrl: "https://flagcdn.com/w160/de.png",
    ranking: 12, worldCupWins: 4, titles: ["1954", "1974", "1990", "2014"],
    description: "Tetracampeã mundial, a Alemanha liderou o Grupo E e avançou para o mata-mata em 2026.",
    isUnbeaten: false,
  },
  {
    id: "ecu", name: "Equador", group: "E",
    flagUrl: "https://flagcdn.com/w160/ec.png",
    ranking: 44, worldCupWins: 0, titles: [],
    description: "Com talento sul-americano, o Equador disputou o Grupo E com determinação.",
    isUnbeaten: false,
  },
  {
    id: "civ", name: "Costa do Marfim", group: "E",
    flagUrl: "https://flagcdn.com/w160/ci.png",
    ranking: 47, worldCupWins: 0, titles: [],
    description: "A Costa do Marfim, com uma geração de ouro no passado, busca seu espaço no cenário mundial.",
    isUnbeaten: false,
  },
  {
    id: "cuw", name: "Curaçao", group: "E",
    flagUrl: "https://flagcdn.com/w160/cw.png",
    ranking: 87, worldCupWins: 0, titles: [],
    description: "Estreante na Copa do Mundo, Curaçao representa o crescimento do futebol caribenho.",
    isUnbeaten: false,
  },
  // ─── GRUPO F ──────────────────────────────────────────────────────────────
  {
    id: "ned", name: "Holanda", group: "F",
    flagUrl: "https://flagcdn.com/w160/nl.png",
    ranking: 7, worldCupWins: 0, titles: [],
    description: "Tricampeã europeia e finalista em 1974, 1978 e 2010. Liderou o Grupo F com 7 pontos em 2026.",
    isUnbeaten: false,
  },
  {
    id: "jpn", name: "Japão", group: "F",
    flagUrl: "https://flagcdn.com/w160/jp.png",
    ranking: 18, worldCupWins: 0, titles: [],
    description: "A seleção mais forte da Ásia avançou em segundo no Grupo F com 5 pontos.",
    isUnbeaten: false,
  },
  {
    id: "tun", name: "Tunísia", group: "F",
    flagUrl: "https://flagcdn.com/w160/tn.png",
    ranking: 28, worldCupWins: 0, titles: [],
    description: "Presença frequente nas Copas, a Tunísia não conseguiu pontos no Grupo F em 2026.",
    isUnbeaten: false,
  },
  {
    id: "swe", name: "Suécia", group: "F",
    flagUrl: "https://flagcdn.com/w160/se.png",
    ranking: 30, worldCupWins: 0, titles: [],
    description: "País de Ibrahimovic e terceiro lugar em 1994, a Suécia ficou em terceiro no Grupo F.",
    isUnbeaten: false,
  },
  // ─── GRUPO G ──────────────────────────────────────────────────────────────
  {
    id: "bel", name: "Bélgica", group: "G",
    flagUrl: "https://flagcdn.com/w160/be.png",
    ranking: 3, worldCupWins: 0, titles: [],
    description: "A Geração de Ouro da Bélgica, terceiro lugar em 2018, liderou o Grupo G em 2026.",
    isUnbeaten: false,
  },
  {
    id: "irn", name: "Irã", group: "G",
    flagUrl: "https://flagcdn.com/w160/ir.png",
    ranking: 20, worldCupWins: 0, titles: [],
    description: "A seleção mais forte da Ásia Ocidental, o Irã disputa Copas com regularidade.",
    isUnbeaten: false,
  },
  {
    id: "egy", name: "Egito", group: "G",
    flagUrl: "https://flagcdn.com/w160/eg.png",
    ranking: 35, worldCupWins: 0, titles: [],
    description: "Sete vezes campeão africano, o Egito voltou ao palco mundial com Salah no auge.",
    isUnbeaten: false,
  },
  {
    id: "nzl", name: "Nova Zelândia", group: "G",
    flagUrl: "https://flagcdn.com/w160/nz.png",
    ranking: 96, worldCupWins: 0, titles: [],
    description: "Representante da Oceania, a Nova Zelândia faz sua estreia histórica em mais uma Copa.",
    isUnbeaten: false,
  },
  // ─── GRUPO H ──────────────────────────────────────────────────────────────
  {
    id: "esp", name: "Espanha", group: "H",
    subtitle: "Campeã 2026",
    flagUrl: "https://flagcdn.com/w160/es.png",
    ranking: 8, worldCupWins: 2, titles: ["2010", "2026"],
    description: "Bicampeã mundial — 2010 e 2026 — e com 4 títulos europeus. Dominou o Grupo H e ergueu a taça.",
    isUnbeaten: true,
  },
  {
    id: "uru", name: "Uruguai", group: "H",
    flagUrl: "https://flagcdn.com/w160/uy.png",
    ranking: 17, worldCupWins: 2, titles: ["1930", "1950"],
    description: "Bicampeão mundial em 1930 e 1950, o Uruguai é uma das grandes potências históricas do futebol.",
    isUnbeaten: false,
  },
  {
    id: "ksa", name: "Arábia Saudita", group: "H",
    flagUrl: "https://flagcdn.com/w160/sa.png",
    ranking: 56, worldCupWins: 0, titles: [],
    description: "Memorable pela vitória sobre a Argentina em 2022, a Arábia Saudita investe pesado no futebol.",
    isUnbeaten: false,
  },
  {
    id: "cpv", name: "Cabo Verde", group: "H",
    flagUrl: "https://flagcdn.com/w160/cv.png",
    ranking: 73, worldCupWins: 0, titles: [],
    description: "Estreante na Copa do Mundo, Cabo Verde escreve sua história no futebol africano.",
    isUnbeaten: false,
  },
  // ─── GRUPO I ──────────────────────────────────────────────────────────────
  {
    id: "fra", name: "França", group: "I",
    flagUrl: "https://flagcdn.com/w160/fr.png",
    ranking: 2, worldCupWins: 2, titles: ["1998", "2018"],
    description: "Bicampeã mundial em 1998 e 2018, a França terminou em quarto lugar na Copa 2026.",
    isUnbeaten: false,
  },
  {
    id: "sen", name: "Senegal", group: "I",
    flagUrl: "https://flagcdn.com/w160/sn.png",
    ranking: 25, worldCupWins: 0, titles: [],
    description: "Campeão africano em 2021 e 2022, o Senegal é uma das forças do continente.",
    isUnbeaten: false,
  },
  {
    id: "nor", name: "Noruega", group: "I",
    flagUrl: "https://flagcdn.com/w160/no.png",
    ranking: 26, worldCupWins: 0, titles: [],
    description: "Liderada por Haaland, a Noruega surpreendeu ao avançar do Grupo I e eliminar o Brasil.",
    isUnbeaten: false,
  },
  {
    id: "irq", name: "Iraque", group: "I",
    flagUrl: "https://flagcdn.com/w160/iq.png",
    ranking: 68, worldCupWins: 0, titles: [],
    description: "Representante do futebol árabe, o Iraque disputou sua primeira Copa do Mundo desde 1986.",
    isUnbeaten: false,
  },
  // ─── GRUPO J ──────────────────────────────────────────────────────────────
  {
    id: "arg", name: "Argentina", group: "J",
    subtitle: "Vice-campeã 2026",
    flagUrl: "https://flagcdn.com/w160/ar.png",
    ranking: 1, worldCupWins: 3, titles: ["1978", "1986", "2022"],
    description: "Tricampeã mundial — 1978, 1986 e 2022 —, a Argentina dominou o Grupo J e chegou à final.",
    isUnbeaten: false,
  },
  {
    id: "aut", name: "Áustria", group: "J",
    flagUrl: "https://flagcdn.com/w160/at.png",
    ranking: 24, worldCupWins: 0, titles: [],
    description: "Com um futebol moderno e intenso, a Áustria avançou do Grupo J como vice-líder.",
    isUnbeaten: false,
  },
  {
    id: "alg", name: "Argélia", group: "J",
    flagUrl: "https://flagcdn.com/w160/dz.png",
    ranking: 31, worldCupWins: 0, titles: [],
    description: "Campeã africana em 2019, a Argélia avançou do Grupo J como um dos melhores terceiros.",
    isUnbeaten: false,
  },
  {
    id: "jor", name: "Jordânia", group: "J",
    flagUrl: "https://flagcdn.com/w160/jo.png",
    ranking: 70, worldCupWins: 0, titles: [],
    description: "Estreante absoluta na Copa do Mundo, a Jordânia representa o crescimento do futebol árabe.",
    isUnbeaten: false,
  },
  // ─── GRUPO K ──────────────────────────────────────────────────────────────
  {
    id: "por", name: "Portugal", group: "K",
    flagUrl: "https://flagcdn.com/w160/pt.png",
    ranking: 6, worldCupWins: 0, titles: [],
    description: "Terceiro lugar em 1966, Portugal chega à Copa 2026 com uma nova geração de estrelas.",
    isUnbeaten: false,
  },
  {
    id: "col", name: "Colômbia", group: "K",
    flagUrl: "https://flagcdn.com/w160/co.png",
    ranking: 9, worldCupWins: 0, titles: [],
    description: "A Colômbia surpreendeu ao liderar o Grupo K com 7 pontos, acima de Portugal.",
    isUnbeaten: false,
  },
  {
    id: "uzb", name: "Uzbequistão", group: "K",
    flagUrl: "https://flagcdn.com/w160/uz.png",
    ranking: 65, worldCupWins: 0, titles: [],
    description: "Estreante na Copa do Mundo, o Uzbequistão representa a Central Ásia no cenário global.",
    isUnbeaten: false,
  },
  {
    id: "cod", name: "RD Congo", group: "K",
    flagUrl: "https://flagcdn.com/w160/cd.png",
    ranking: 53, worldCupWins: 0, titles: [],
    description: "Uma das maiores potências do futebol africano, o Congo avançou como um dos melhores terceiros.",
    isUnbeaten: false,
  },
  // ─── GRUPO L ──────────────────────────────────────────────────────────────
  {
    id: "eng", name: "Inglaterra", group: "L",
    subtitle: "3º Lugar 2026",
    flagUrl: "https://flagcdn.com/w160/gb-eng.png",
    ranking: 4, worldCupWins: 1, titles: ["1966"],
    description: "A terra do futebol, campeã em 1966. Na Copa 2026, chegou ao 3º lugar derrotando a França por 6 a 4.",
    isUnbeaten: false,
  },
  {
    id: "cro", name: "Croácia", group: "L",
    flagUrl: "https://flagcdn.com/w160/hr.png",
    ranking: 10, worldCupWins: 0, titles: [],
    description: "Vice-campeã em 2018 e terceiro lugar em 2022, a Croácia avançou do Grupo L como segundo.",
    isUnbeaten: false,
  },
  {
    id: "pan", name: "Panamá", group: "L",
    flagUrl: "https://flagcdn.com/w160/pa.png",
    ranking: 51, worldCupWins: 0, titles: [],
    description: "Avançou como um dos melhores terceiros colocados no Grupo L.",
    isUnbeaten: false,
  },
  {
    id: "gha", name: "Gana", group: "L",
    flagUrl: "https://flagcdn.com/w160/gh.png",
    ranking: 60, worldCupWins: 0, titles: [],
    description: "Quinto lugar no Grupo L, Gana é uma das forças emergentes do futebol africano.",
    isUnbeaten: false,
  },
];
